version: "3.9"
services:
  app-front:
    build:
        dockerfile: server.dockerfile
        context: .
    image: app-front:latest
    container_name: app-front
    ports:
        - "8080:8080"
    volumes:
        - ./:/app
        - ./server/:/etc/nginx/conf.d/
        - node_modules:/app/node_modules
        - dist:/app/dist
volumes:
  node_modules:
  dist: